"""Model construction, training, evaluation, and persistence helpers."""

from run_core import (
    as_2d_float_array,
    as_feature_matrix,
    compute_regression_report_metrics,
    cross_validate_model,
    dataframe_from_tabular,
    fit_model,
    fit_model_on_split,
    fit_sklearn_model,
    initialize_linear_weights,
    inverse_transform_dataframe,
    is_torch_model,
    load_model_state_dict,
    make_torch_model,
    repeat_fit_model,
    safe_r2_score,
    save_run_summary,
    select_epochs_with_cv_early_stopping,
    set_model_seed,
    sklearn_model_supports_multioutput,
    target_dataframe,
    transform_dataframe,
    validate_hidden_size_compatibility,
)
